import dataset from "../data/holidays.json";
import { Calculator } from "./calculator";

export default function Home(){const year=2026;const holidays=dataset.occurrences.filter(item=>(item.date?.startsWith(String(year))??item.id.endsWith(String(year))));return <main>
  <header><a className="brand" href="https://digitalghana.dev"><i/>Digital Ghana</a><nav><a href="#calendar">2026 calendar</a><a href="#developers">Developers</a><a href="https://github.com/stanleyHayes/ghanacalendar">GitHub</a></nav></header>
  <section className="hero"><p className="eyebrow">GhanaCalendar · dataset {dataset.version}</p><h1>Working days,<br/><em>without guesswork.</em></h1><div className="hero-copy"><p>Evidence-backed public holidays and deterministic business-day calculations for payroll, fintech, logistics, scheduling, and every Ghana-aware product.</p><span>Timezone locked to<br/><b>Africa/Accra</b></span></div></section>
  <section className="tool"><div><p className="eyebrow">Try the rules engine</p><h2>Add working days</h2><p>Weekends, statutory holidays, and confirmed observed dates are skipped. Pending movable holidays are never invented.</p></div><Calculator holidays={holidays}/></section>
  <section className="calendar" id="calendar"><div className="section-title"><p className="eyebrow">Official 2026 register</p><h2>Confirmed dates</h2><p>Movable dates stay visibly pending until an official notice confirms them.</p></div><ol>{holidays.map(item=><li key={item.id} className={item.status==="pending"?"pending":""}><time>{item.date?new Intl.DateTimeFormat("en-GH",{day:"2-digit",month:"short",timeZone:"UTC"}).format(new Date(`${item.date}T12:00:00Z`)):"TBC"}</time><div><strong>{item.name}</strong>{item.observedDate&&<small>Observed {item.observedDate}</small>}</div><span>{item.status}</span></li>)}</ol><div className="exports"><a href="https://api-calendar.digitalghana.dev/v1/holidays?year=2026&format=ics">Download ICS ↗</a><a href="https://api-calendar.digitalghana.dev/v1/holidays?year=2026&format=csv">Download CSV ↗</a></div></section>
  <section className="developers" id="developers"><div><p className="eyebrow">One answer across interfaces</p><h2>Built for software,<br/>readable by people.</h2></div><div className="endpoint"><span>REST</span><code>GET /v1/working-day?date=2026-07-03</code><pre>{`{"date":"2026-07-03","workingDay":false,"timezone":"Africa/Accra"}`}</pre></div><div className="features"><p><b>Historical by default</b>Rules apply to their effective period. A 2025 amendment never changes a 2024 answer.</p><p><b>Source-linked</b>Every occurrence names the Ministry notice or legal source behind it.</p><p><b>Useful exports</b>JSON for applications, CSV for analysis, and ICS for calendars.</p></div></section>
  <section className="source"><p className="eyebrow">Source and limits</p><p>Calendar facts are transcribed from Ghana Ministry of the Interior notices with attribution. Source documents are linked, not republished. This independent open-source project does not imply government endorsement.</p><a href="https://github.com/stanleyHayes/ghanacalendar/blob/main/docs/governance/source-register.json">Review the source register ↗</a></section>
  <footer><strong>GhanaCalendar</strong><span>A Digital Ghana public-infrastructure project.</span><a href="mailto:hello@digitalghana.dev">Report a correction</a></footer>
</main>}
